name: les_social
description: LesMind

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  jwt_io: ^1.1.6
  cupertino_icons: ^1.0.2
  google_sign_in: ^6.1.6
  percent_indicator: ^4.2.2
  cached_network_image: ^3.0.0
  flutter_spinkit: ^5.0.0
  fluttertoast: ^8.0.7
  animations: ^2.0.0
  image: ^4.1.6
  uuid: ^4.2.2
  image_picker: ^1.0.7
  path_provider: ^2.0.2
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  url_launcher: ^6.2.2
  get: ^4.6.6
  timeago: ^3.1.0
  google_fonts: ^6.1.0
  provider: ^6.0.3
  image_cropper: ^6.0.0
  shared_preferences: ^2.0.6
  ionicons: ^0.2.1
  intl: ^0.19.0
  loading_overlay: ^0.3.0
  like_button: ^2.0.5
  flutter_chat_bubble: ^2.0.0
  permission_handler: ^11.0.1
  story: ^1.1.0
  story_view: ^0.16.0
  flutter_local_notifications: ^17.2.0
  badges: ^3.1.2
  carousel_slider: ^4.2.1
  font_awesome_flutter: ^10.7.0
  flutter_launcher_icons: ^0.13.1
  animated_background: ^2.0.0
  dio: ^5.4.3+1
  jwt_decode: ^0.3.1
  jwt_decoder: ^2.0.1
  dart_jsonwebtoken: ^2.14.0
  cookie_jar: ^4.0.8
  mockito: ^5.4.4
  zefyr: ^1.0.0-rc.5
  zefyrka: ^1.5.0
  flutter_webrtc: ^0.12.3
  web_socket: ^0.1.6
  web_socket_channel: ^3.0.1
  onesignal_flutter: ^5.2.8
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/lesmin-background.png"

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true


  assets:
    - assets/images/login.png
    - assets/images/new1.png
    - assets/images/wooble2.jpg
    - assets/images/wooble3.jpg
    - assets/images/friendship.jpeg
    - assets/images/gay.jpg
    - assets/images/les1.jpg
    - assets/images/les2.jpg
    - assets/images/les3.jpg
    - assets/images/les4.jpg
    - assets/images/les5.jpg
    - assets/images/les6.jpg
    - assets/images/gay.jpg
    - assets/images/les7.jpg
    - assets/images/les.jpg
    - assets/images/lesmind.png
    - assets/images/lesmin-background.png
    - assets/images/google.png
    - assets/images/google2.png
    - assets/images/apple.png
    - assets/images/profile_avatar.png
#    - packages/timeago/lookupmessages_pl.json
    - assets/lookupmessages_pl.json
    - assets/likes_pl.json
    - assets/comments_pl.json
