name: les_social
description: LesMind

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_sign_in: ^6.1.6
  percent_indicator: ^4.2.2
  cached_network_image: ^3.0.0
  flutter_spinkit: ^5.0.0
  cloud_firestore: ^4.14.0
  fluttertoast: ^8.0.7
  animations: ^2.0.0
  image: ^4.1.6
  uuid: ^4.2.2
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  image_picker: ^1.0.7
  firebase_storage: ^11.6.0
  path_provider: ^2.0.2
  geolocator: ^11.0.0
  geocoding: ^2.0.0
  url_launcher: ^6.2.2
  get: ^4.6.6
  timeago: ^3.1.0
  google_fonts: ^6.1.0
  provider: ^6.0.3
  image_cropper: ^5.0.1
  shared_preferences: ^2.0.6
  ionicons: ^0.2.1
  loading_overlay: ^0.3.0
  like_button: ^2.0.4
  flutter_chat_bubble: ^2.0.0
  permission_handler: ^11.0.1
  story: ^1.1.0
  story_view: ^0.16.0
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^16.3.2
  badges: ^3.1.2
  carousel_slider: ^4.2.1
  firebase_crashlytics: ^3.4.9
  firebase_analytics: ^10.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true


  assets:
    - assets/images/login.png
    - assets/images/new1.png
    - assets/images/wooble2.jpg
    - assets/images/wooble3.jpg
    - assets/images/friendship.jpeg
    - assets/images/gay.jpg
    - assets/images/les1.jpg
    - assets/images/les2.jpg
    - assets/images/les3.jpg
    - assets/images/les4.jpg
    - assets/images/les5.jpg
    - assets/images/les6.jpg
    - assets/images/gay.jpg
    - assets/images/les7.jpg
    - assets/images/les.jpg
    - assets/images/lesmind.png
    - assets/images/google.png
    - assets/images/google2.png
    - assets/images/apple.png
    - assets/images/profile_avatar.png