// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDls_zOAYos3khqWN3I0lDd8nWFy-cZOos',
    appId: '1:209210387730:web:1a264d953911a90c99d7cb',
    messagingSenderId: '209210387730',
    projectId: 'les-social',
    authDomain: 'les-social.firebaseapp.com',
    storageBucket: 'les-social.appspot.com',
    measurementId: 'G-V2NKRS86HT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJ6o2nJKYmlIBpwURsddsyOCY8gsKXoLM',
    appId: '1:209210387730:android:4ecdb4d4a871ac2799d7cb',
    messagingSenderId: '209210387730',
    projectId: 'les-social',
    storageBucket: 'les-social.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhkbKQLxyiJL2ZoEfFkn__PfyJ3jx0D7E',
    appId: '1:209210387730:ios:544c3f116b6c7db699d7cb',
    messagingSenderId: '209210387730',
    projectId: 'les-social',
    storageBucket: 'les-social.appspot.com',
    iosBundleId: 'studio.aleksandraweber.lesSocial',
  );
}
